name: Run Tests & Upload to Coveralls
on: [push, pull_request]  # Runs on every push or PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full commit history for Coveralls

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests & Generate Coverage
      run: npm test -- --coverage

    - name: Upload Coverage to Coveralls
      id: coveralls
      uses: coverallsapp/github-action@v2
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}  # Use GitHub Secret
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true
        flag-name: ubuntu-latest
        debug: true
        service_number: ${{ github.run_id }}

    - name: Finalize Coveralls Parallel Builds
      if: always()
      run: |
        curl -X POST "https://coveralls.io/webhook" \
          -H "Content-Type: application/json" \
          -d "{\"repo_token\": \"${{ secrets.COVERALLS_REPO_TOKEN }}\", \"payload\": {\"build_num\": \"${{ github.run_id }}\", \"status\": \"done\"}}"
          